### ISSUE TITLE
Sensitivity compensation

### ISSUE THREAD

**Issue by kenjif70** [enjoyneering/BH1750FVI#1]
Thanks for developing this library. I just bought a breakout board with BH1750FVI and found this library works great!

But one thing I found is that readLightLevel gives a very different value when the sensitivity is changed from 1 to another. I believe the reason is that, in the readLightLevel method, rawLightLevel is multiplied by _sensitivity. If I divided by _sensitivity, it could give me consistent values regardless of the sensitivity. Could you take a look? Thanks in advance.

**Comment by enjoyneering** [comment]
Did you read README.md? Sensitivity used for another purpose.

Any optical filter you put in front of the sensor blocks some light. Sensitivity is used to **compensate the influence of the optical filter**.  For example, when transmission rate of optical window is 50% (measurement result becomes 0.5 times lower), influence of optical window is ignored by changing sensor sensitivity from default 1.0 to 2.0 times

I did not invent it, it is from the datasheet

**Comment by kenjif70** [comment]
Yes, I know. To compensate the influence of the optical filter, a sensor readout needs to be divided by _sensitivity. Currently, your library gives x4 bigger number when you set the sensitivity to x2, for example.

Here's an except from the datasheet. Note that it's multiplies by (69 / X) but not (X / 69).

> The below formula is to calculate illuminance per 1 count.
> 
> H-reslution mode : Illuminance per 1 count ( lx / count ) = 1 / 1.2 ***( 69 / X )**
> H-reslution mode2 : Illuminance per 1 count ( lx / count ) = 1 / 1.2 ***( 69 / X )** / 2
> 
> 1.2 : Measurement accuracy
> 69 : Default value of MTreg ( dec )
> X : MTreg value

**Comment by enjoyneering** [comment]
Thank you.  I'll doble check.

**Comment by enjoyneering** [comment]
Sorry for delay. Looks like I simplified the equations correctly. Double checked it with math software, [see link for details](https://ibb.co/kqFgBzG).

**Comment by kenjif70** [comment]
A table at the bottom of p.11 shows (lx / count) values. For example, if ADC count = 1000 in H-resolution mode with MTreg=31, lx should be 1.85 * 1000 = 1850 (not 374.396).

**Comment by enjoyneering** [comment]
You are right!!! Will fix it this week. Thank you.

**Comment by enjoyneering** [comment]
done
