### ISSUE TITLE
integrationTime in readLightLevel

### ISSUE THREAD

**Issue by randombitflip** [enjoyneering/BH1750FVI#2]
Dear @enjoyneering,

was it your intention that other modes than `BH1750_ONE_TIME_HIGH_RES_MODE_2`, `BH1750_ONE_TIME_LOW_RES_MODE `do have a integration time greater than zero? 
My understanding is that in continuous operation mode you don't have to necessarily wait before reading out the sensor.

If it wasn't your intention you could add a break statement after each case of `switch(_sensorResolution)`. If it is your intention you might want to adjust the documentation string of `readLightLevel `accordingly.

Thanks for consideration and kind regards,
randombitflip

**Comment by enjoyneering** [comment]
Good question!!! According to the datasheet, in continuous mode, we must wait for the completion of the 1st measurement. The problem is that the library does not know if it is the first measurement or not.

**Comment by randombitflip** [comment]
Thank you for your reply. As I interpret the datasheet (BH1750FVI - 2011.11 - Rev.D)  it doesn't explicitly state that we **must** wait. Furthermore on page 5 they state that the illuminace data register will have value '0' after reset/ first power on.

Let's do some theoretical thinking on this in "H-resolution mode":
If we read out the illuminance before we send a "Continuously H-resolution mode" we would receive the value '0'.
If we then issue the "continious mode instruction", we could in theory also read the register immediatly after it and we would still get the value '0'.
If we wait at least 180ms (page 7) after we issued the "continious mode instruction" we can be certain, that the sensor updated the register and we will receive a value which represents the first measured illuminance if we read out the register.
If we wait another 120ms (page 7) "typically"  the illuminace register should have been updated with the second measurement and so on.

Would you agree on those points?

**Comment by enjoyneering** [comment]
Yes, I agree.

BH1750FVI - 2011.11 - Rev.D on page 7

![Capture](https://user-images.githubusercontent.com/10623649/111770829-484b8680-8881-11eb-988e-330860d80a8d.PNG)

**Comment by randombitflip** [comment]
Okay let's formulate it in a different way:

As a user of this library I didn't expect that the call of `readLightLevel` in continuous h-res mode blocks my calling thread unnecessarily for 180ms each time. From my point of view 180ms is a really huge amount of time which I could better use for other important stuff in my program. Further more you might want to rethink the errorhandling (actually another issue). As it is now, from a user perspective, you can't distinguish whether the sensor reading is 0 or the I2C connection is broken. 
Take those points as constructive feedback which you maybe take into consideration in future releases.

**Comment by enjoyneering** [comment]
I agree randombitflip - it is blocking the code for 180ms & you can't tell if it 0 or the I2C connection is broken.

I personally do not like "if (mills() - lastMills > 180)....". It is hard to read, it takes RAM. Also the Arduino Core itself is very slow. This why I prefer delay(). You cannot spoil what is already spoiled. If I was using Microchip Studio I would definitely replace the delay() with an ISR timer.

As for "0 or the I2C connection is broken", I don't know how to fix it.  The Arduino I2C library doesn't give a lot of information about bus errors. If you have any ideas how to do it, let me know.

**Comment by randombitflip** [comment]
Regarding the blocking function calls: I guess it is personal preference how you want to handle those cases, were you have to wait for sensors doing their conversion ;)

Regarding the "0 or the I2C connection is broken": From my point of view the actual problem is, that the defined error value lies within the valid value range of the sensor.  I would suggest to change the value of  `BH1750_ERROR` from
```c
#define BH1750_ERROR 0x00  //returns 0, if communication error has occurred
```

to

```c
#define BH1750_ERROR 0xFFFFFFFF //returns float min, if communication error has occurred
```

this way users can check in their application wheather the sensor reads 0 lx or the connection is broken. Here is an example of my application code:

```c
void cmd_get_value(GetSensorValueRequest * a_req, GetSensorValueResponse * a_resp){
    auto ti_conv_us = micros();
    float value = m_obj_drv.readLightLevel(); // [lx]
    if (value == BH1750_ERROR){
        a_resp->flg_det_error = true;
        a_resp->value =  0.0f; // [lx] - set default value in case of an error
    } else {
        a_resp->flg_det_error = false;
        a_resp->value = value; // [lx]
    }
    a_resp->ti_conv_us = (uint32_t)(micros() - ti_conv_us); // [us]
}
```

By checking `a_resp->flg_det_error` I can check if the sensor reading was valid.

By the way your code runs on a ESP32 so you might want to add it to your tested platforms in your readme.md.
